export const HashTagIds = [
  {id: 0, name: '펑키'},
  {id: 1, name: '발라드'},
  {id: 2, name: '랩'},
  {id: 3, name: '팝송'},
  {id: 4, name: '재즈'},
  {id: 5, name: '포크'},
  {id: 6, name: '디스코'},
  {id: 7, name: '트로트'},
  {id: 8, name: '댄스'},
  {id: 9, name: 'EDM'},
  {id: 10, name: '클래식'},
  {id: 11, name: '락&롤'},
  {id: 12, name: '블루스'},
  {id: 13, name: '컨트리'},
  {id: 14, name: '레게'},
  {id: 15, name: 'K-POP'},
  {id: 16, name: 'J-POP'},
  {id: 17, name: 'R&B'},
  {id: 18, name: '오페라'},
  {id: 19, name: '인디'},
  {id: 20, name: '교향곡'},
  {id: 21, name: '메탈'},
  {id: 22, name: '샹송'},
  {id: 23, name: '성악'},
];

export const OnboardingDatas = [
  {
    _id: '1',
    title: 'Play the music ',
    description: 'Ssimille를 이용해 음악을 마음껏 들어주세요',
    img: require('./assets/Guitar.png'),
  },
  {
    _id: '2',
    title: 'Have communication',
    description: '사람들과 커뮤니티 및 채팅을 즐기며 지내주세요 ',
    img: require('./assets/Enjoy.png'),
  },
  {
    _id: '3',
    title: 'Ssimille will introduce you to a friend',
    description: 'Ssimille가 당신에게 친구를 만들어 드리겠습니다.',
    img: require('./assets/Selfi.png'),
  },
];
