const itemIds = [
    {id: 0, name: '펑키'},
    {id: 1, name: '발라드'},
    {id: 2, name: '랩'},
    {id: 3, name: '팝송'},
    {id: 4, name: '재즈'},
    {id: 5, name: '포크'},
    {id: 6, name: '디스코'},
    {id: 7, name: '트로트'},
    {id: 8, name: '댄스'},
    {id: 9, name: 'EDM'},
    {id: 10, name: '클래식'},
    {id: 11, name: '락&롤'},
    {id: 12, name: '블루스'},
    {id: 13, name: '컨트리'},
    {id: 14, name: '레게'},
    {id: 15, name: 'k-pop'},
    {id: 16, name: 'j-pop'},
    {id: 17, name: 'R&B'},
    {id: 18, name: '오페라'},
    {id: 19, name: '인디'},
    {id: 20, name: '교향곡'},
    {id: 21, name: '메탈'},
    {id: 22, name: '샹송'},
    {id: 23, name: '성악'},
];
  
export default itemIds;