const types = {
  UPLOAD_PROFILE_IMG: 'UPLOAD_PROFILE_IMG',
  UPDATE_PROFILE_IMG: 'UPDATE_PROFILE_IMG',
  SAVE_KAKAO_UID: 'SAVE_KAKAO_UID',
  SAVE_SPOTIFY_TOKEN: 'SAVE_SPOTIFY_TOKEN',
};

export default types;
