const types = {
  UPLOAD_PROFILE_IMG: 'UPLOAD_PROFILE_IMG',
  SAVE_KAKAO_UID: 'SAVE_KAKAO_UID',
  SAVE_SPOTIFY_TOKEN: 'SAVE_SPOTIFY_TOKEN',
  SAVE_USER_PROFILE: 'SAVE_USER_PROFILE',
  SAVE_USER_LOCATION: 'SAVE_USER_LOCATION',
  SAVE_MY_POST: 'SAVE_MY_POST',
  SAVE_USER_LOCATION_NAME: 'SAVE_USER_LOCATION_NAME',
};

export default types;
